service: expressmeta-nextjs
runtime: nodejs14
instance_class: F4
automatic_scaling:
  max_instances: 10
  min_instances: 1
  min_idle_instances: 1
  max_idle_instances: 1
  min_pending_latency: automatic
  max_pending_latency: automatic
handlers:
  - url: /.*
    secure: always
    script: auto

